# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 66d934ef32381b32ab89f9cc2ba07024d703e1a10dc5e369413f78a6b2219eb8dc83d112e88e25ce4701e1c809c021d00906b761e26f0a438a28cc43203da33f

test:
  secret_key_base: 8ba134a77565ffae1fc2a4142dd669cea8bf7aee0b15e17bd110d26085968a3ecfb5aa856b68967bc6bb9fdce9392c033ab4b07e2642f7f56ec2e6290220c26c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
